root: true
extends: eslint:recommended
parser: babel-eslint
env:
  node: true
  es6: true
rules:
  semi:
    - warn
    - always
  quotes:
    - error
    - single
  indent:
    - error
    - tab
  arrow-body-style:
    - error
    - always
  comma-spacing: 
    - warn
    - { "before": false, "after": true }
  no-proto: 
    - error
  max-len:
    - error
    - { "code": 90 }
  max-depth:
    - error
    - 4
  multiline-ternary:
    - error
    - always
  operator-linebreak:
    - error
    - before
  object-curly-newline:
    - error
    - always

