name: service-product-search-workflow-default

on:
  push:
    branches:
      service/product-search
  pull_request:
    branches:
      service/product-search
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
      - name: Check nodejs version
        run: node -v
      - name: Clean install dependencies and audit
        run: |
          npm ci
          npm audit
      - name: test
        run: npm run-script test
